default:
  tags:
    - docker

stages:
  - push

push_to_github:
  stage: push
  only:
    - main
  script:
    - git config --global user.email "johndgraham@mac.com"
    - git config --global user.name "John Graham"
    - git remote add github https://john-graham:${GITHUB_ACCESS_TOKEN}@github.com/john-Graham/uw-guide-plugin.git
    - git fetch --unshallow || true  # Ensures you have a complete history if the repository was initially cloned with a shallow copy
    - git push github HEAD:main
