default:
  tags:
    - docker
image: alpine/git
stages:
  - push
push_to_github:
  stage: push
script:
  - 'echo "Current shell: $SHELL"'
  - which sh
  - which git
  - git config --global user.email "johndgraham@mac.com"
  - git config --global user.name "John Graham"
  - git remote remove github || true
  - git remote add github
    https://john-graham:${GITHUB_ACCESS_TOKEN}@github.com/john-Graham/uw-guide-plugin.git
  - git fetch --unshallow || true
  - git push github HEAD:main
